query getActividades($page:Int,$number_paginate:Int, $estado:Int) {
  actividades(page:$page,number_paginate:$number_paginate, estado:$estado){
      nroTotal_items
      data{
        id
        titleActivity
        slugtitleActivity
        textActivity
        keywords
        description
        imagenDestacada
        galleryActivity
        categoryActivity_id
        estado
      }
  }
}
